[tools]
node = "22.17.0"

[tasks.npx]
usage = '''
arg "<cmd>"
arg "<rest>..."
complete "cmd" run="ls ./node_modules/.bin"
'''
# run = [
#   "echo cmd: {{arg(name='cmd')}}",
#   "echo rest: {{arg(name='rest')}}",
# ]
run = "./node_modules/.bin/{{arg(name='cmd')}} {{arg(name='rest')}}"

[tasks.node-rebuild]
hide = true
run = "npm rebuild"

[tasks.dev]
# depends = ["node-rebuild"]
run = "bun run dev"

[tasks.electron-dev]
run = """
  mprocs \
    "bun run dev" \
    "wait-on http://localhost:3005 && electron ."
"""

[tasks.build]
run = "mise npx electron-forge make"
alias = "make"

[tasks.package]
run = "mise npx electron-forge package"

[tasks.unpack]
run = "mise npx @electron/asar extract"
